[project]
name = "dfs-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["networkx", "matplotlib", "ipywidgets","numpy","jupyter","plotext","flask"]
